import { Product } from "@/types";

export const products: Product[] = [
  {
    id: "p001",
    name: "Orbital Chrono X",
    slug: "orbital-chrono-x",
    shortDescription: "Titanium case with sapphire crystal and precision movement.",
    description:
      "The Orbital Chrono X represents the apex of horological engineering. Machined from aerospace-grade titanium, its case weighs a mere 68 grams while maintaining uncompromising rigidity. The sapphire crystal exhibition caseback reveals a hand-finished movement with 72-hour power reserve. Water resistant to 300 meters with a ceramic bezel that resists scratches for decades.",
    price: 4890,
    originalPrice: 5800,
    category: "watches",
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
      "https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=800&q=80",
      "https://images.unsplash.com/photo-1622434641406-a158123450f9?w=800&q=80",
    ],
    colors: [
      { name: "Midnight", hex: "#1a1a2e" },
      { name: "Titanium", hex: "#878787" },
      { name: "Rose Gold", hex: "#b8764a" },
    ],
    rating: 4.9,
    reviewCount: 284,
    stock: 12,
    tags: ["luxury", "titanium", "swiss", "chronograph"],
    featured: true,
    new: false,
    modelColor: "#1a1a2e",
    specs: {
      "Case Material": "Grade 5 Titanium",
      "Case Diameter": "42mm",
      "Crystal": "Sapphire, Anti-reflective",
      "Movement": "Automatic, In-house Caliber",
      "Power Reserve": "72 Hours",
      "Water Resistance": "300m / 1000ft",
      "Strap": "Titanium bracelet with ceramic folding clasp",
      "Warranty": "5 Years",
    },
  },
  {
    id: "p002",
    name: "Aura Pro Headphones",
    slug: "aura-pro-headphones",
    shortDescription: "Planar magnetic drivers with neural noise cancellation.",
    description:
      "Aura Pro redefines what headphones can be. Custom planar magnetic drivers deliver reference-quality audio with zero distortion across the entire frequency spectrum. Neural noise cancellation learns your environment and adapts in real-time. The headband is cast from a single piece of aircraft aluminum, then hand-wrapped in full-grain Italian leather.",
    price: 1290,
    originalPrice: undefined,
    category: "audio",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&q=80",
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80",
    ],
    colors: [
      { name: "Obsidian", hex: "#0d0d0d" },
      { name: "Arctic", hex: "#f0f0f0" },
      { name: "Forest", hex: "#2d4a3e" },
    ],
    rating: 4.8,
    reviewCount: 512,
    stock: 45,
    tags: ["planar", "audiophile", "noise-cancelling", "premium"],
    featured: true,
    new: true,
    modelColor: "#0d0d0d",
    specs: {
      "Driver": "70mm Planar Magnetic",
      "Frequency Response": "5Hz - 80kHz",
      "Impedance": "32Ω",
      "Sensitivity": "105 dB/mW",
      "Battery Life": "40 hours (ANC on)",
      "Charging": "USB-C, 15min = 5hrs",
      "Connectivity": "Bluetooth 5.3, 3.5mm, 4.4mm",
      "Weight": "310g",
    },
  },
  {
    id: "p003",
    name: "Lumina Desk Lamp",
    slug: "lumina-desk-lamp",
    shortDescription: "Circadian-aware lighting with haptic touch controls.",
    description:
      "Lumina understands that light shapes your day. Its AI core continuously monitors time, ambient conditions, and your stated preferences to maintain the optimal light environment. The arm is forged from a single piece of die-cast aluminum, powder-coated in a proprietary process that eliminates micro-scratches. The diffuser is blown borosilicate glass.",
    price: 680,
    originalPrice: undefined,
    category: "lifestyle",
    images: [
      "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80",
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
      "https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=800&q=80",
    ],
    colors: [
      { name: "Matte Black", hex: "#1c1c1c" },
      { name: "Ivory", hex: "#f5f0e8" },
      { name: "Sage", hex: "#8a9e88" },
    ],
    rating: 4.7,
    reviewCount: 193,
    stock: 28,
    tags: ["smart", "circadian", "minimal", "desk"],
    featured: false,
    new: true,
    modelColor: "#1c1c1c",
    specs: {
      "Light Source": "Full-spectrum LED Array",
      "Color Temperature": "2700K - 6500K adaptive",
      "Brightness": "Up to 2000 lumens",
      "CRI": "Ra 98+",
      "Control": "Haptic touch, App, Voice",
      "Connectivity": "Wi-Fi, Bluetooth",
      "Power": "48W max",
      "Arm Reach": "50cm articulating",
    },
  },
  {
    id: "p004",
    name: "Phantom Wallet",
    slug: "phantom-wallet",
    shortDescription: "Full-grain leather with RFID shielding and AirTag slot.",
    description:
      "Phantom is the wallet refined to its purest form. Cut from a single piece of 4oz Horween leather, it develops a rich patina unique to each owner. An integrated RFID shielding layer protects all contactless cards. A machined aluminum slot discreetly houses an Apple AirTag for peace of mind. Holds 6 cards and bills without bulk.",
    price: 245,
    originalPrice: undefined,
    category: "accessories",
    images: [
      "https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80",
      "https://images.unsplash.com/photo-1553532434-5ab5b6b84993?w=800&q=80",
      "https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800&q=80",
    ],
    colors: [
      { name: "Tan", hex: "#c19a6b" },
      { name: "Espresso", hex: "#3c1f0a" },
      { name: "Black", hex: "#0f0f0f" },
    ],
    rating: 4.9,
    reviewCount: 847,
    stock: 100,
    tags: ["leather", "rfid", "minimal", "airtag"],
    featured: true,
    new: false,
    modelColor: "#c19a6b",
    specs: {
      "Material": "Horween Chromexcel Leather",
      "Card Capacity": "6 cards",
      "RFID Protection": "Yes, aluminum layer",
      "AirTag Compatible": "Yes, hidden slot",
      "Dimensions": "85mm × 55mm × 8mm",
      "Weight": "42g",
      "Stitching": "Waxed nylon thread",
      "Origin": "Handcrafted in USA",
    },
  },
  {
    id: "p005",
    name: "Nexus Speaker",
    slug: "nexus-speaker",
    shortDescription: "360° spatial audio in a sculptural ceramic enclosure.",
    description:
      "Nexus transforms any room into a concert hall. Seven custom-tuned drivers arranged in a 360° array create a sound stage that fills the entire space. The enclosure is cast from high-density ceramic — the same material used in aerospace applications — chosen for its unique acoustic properties and thermal stability. Lossless wireless audio up to 24-bit/192kHz.",
    price: 1890,
    originalPrice: 2200,
    category: "audio",
    images: [
      "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80",
      "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    colors: [
      { name: "Pearl White", hex: "#f5f0eb" },
      { name: "Charcoal", hex: "#2d2d2d" },
      { name: "Terracotta", hex: "#8b4a3a" },
    ],
    rating: 4.6,
    reviewCount: 321,
    stock: 18,
    tags: ["spatial", "audiophile", "ceramic", "360"],
    featured: true,
    new: false,
    modelColor: "#f5f0eb",
    specs: {
      "Drivers": "7 custom-tuned (1 tweeter, 2 mid, 4 woofer)",
      "Frequency Response": "20Hz - 40kHz",
      "Max Output": "200W total",
      "Audio Format": "Up to 24-bit / 192kHz",
      "Connectivity": "Wi-Fi 6, Bluetooth 5.3, Optical",
      "Battery": "N/A (mains powered)",
      "Dimensions": "160mm × 280mm",
      "Weight": "3.8kg",
    },
  },
  {
    id: "p006",
    name: "Apex Stylus Pro",
    slug: "apex-stylus-pro",
    shortDescription: "Haptic feedback with 0.1mm precision and infinite scrolling.",
    description:
      "Apex Stylus Pro is engineered for those who demand absolute precision from their creative tools. The housing is machined from solid brass, then PVD-coated for lasting durability. 8,192 levels of pressure sensitivity and sub-millisecond latency make it indistinguishable from traditional media. The crown doubles as a programmable haptic dial.",
    price: 380,
    originalPrice: undefined,
    category: "tech",
    images: [
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=80",
      "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80",
      "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80",
    ],
    colors: [
      { name: "Gunmetal", hex: "#4a4a4a" },
      { name: "Gold", hex: "#c9a84c" },
      { name: "Silver", hex: "#c0c0c0" },
    ],
    rating: 4.8,
    reviewCount: 156,
    stock: 62,
    tags: ["stylus", "creative", "precision", "haptic"],
    featured: false,
    new: true,
    modelColor: "#4a4a4a",
    specs: {
      "Body": "Machined Brass, PVD Coated",
      "Pressure Levels": "8,192",
      "Tilt Support": "Yes, ±60°",
      "Latency": "<1ms",
      "Battery": "Rechargeable, 12hr life",
      "Charging": "Magnetic USB-C",
      "Compatibility": "iPad Pro, Surface, Galaxy Tab",
      "Weight": "22g",
    },
  },
  {
    id: "p007",
    name: "Solstice Ring",
    slug: "solstice-ring",
    shortDescription: "Health monitoring in a 2.5mm surgical-grade titanium band.",
    description:
      "Solstice Ring proves that the most powerful technology is invisible technology. Milled from solid titanium at a 2.5mm profile, it tracks heart rate, SpO2, body temperature, sleep stages, and activity with clinical-grade accuracy. No screen, no notifications — just pure biometric intelligence delivered to your phone each morning.",
    price: 590,
    originalPrice: undefined,
    category: "tech",
    images: [
      "https://images.unsplash.com/photo-1603974372039-adc49044b6bd?w=800&q=80",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=80",
      "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80",
    ],
    colors: [
      { name: "Stealth", hex: "#1a1a1a" },
      { name: "Silver", hex: "#d4d4d4" },
      { name: "Rose", hex: "#c08080" },
    ],
    rating: 4.7,
    reviewCount: 289,
    stock: 34,
    tags: ["health", "wearable", "titanium", "biometric"],
    featured: false,
    new: true,
    modelColor: "#1a1a1a",
    specs: {
      "Material": "Grade 5 Titanium",
      "Profile": "2.5mm wide, 2mm thick",
      "Sensors": "HR, SpO2, Temp, Accelerometer",
      "Battery Life": "7 days",
      "Water Resistance": "100m",
      "Charging": "Wireless magnetic dock",
      "App": "iOS and Android",
      "Sizes": "6, 7, 8, 9, 10, 11",
    },
  },
  {
    id: "p008",
    name: "Mesa Notebook",
    slug: "mesa-notebook",
    shortDescription: "Stone paper pages, Smyth-sewn binding, and digital sync.",
    description:
      "Mesa is a notebook that bridges the analog and digital worlds. Pages are made from calcium carbonate stone — waterproof, tear-resistant, and silky smooth for any writing instrument. Every page is subtly marked with a proprietary pattern that your phone's camera can translate to perfect digital notes. Smyth-sewn binding opens flat at 180 degrees.",
    price: 145,
    originalPrice: undefined,
    category: "lifestyle",
    images: [
      "https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&q=80",
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&q=80",
      "https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=800&q=80",
    ],
    colors: [
      { name: "Natural", hex: "#e8e0d0" },
      { name: "Slate", hex: "#5a6272" },
      { name: "Onyx", hex: "#1a1a1a" },
    ],
    rating: 4.6,
    reviewCount: 402,
    stock: 200,
    tags: ["notebook", "analog", "digital", "stone-paper"],
    featured: false,
    new: false,
    modelColor: "#e8e0d0",
    specs: {
      "Pages": "240 pages (120 leaves)",
      "Paper": "Stone paper, 120gsm equivalent",
      "Ruling": "Dot grid, 5mm",
      "Binding": "Smyth-sewn, lay-flat",
      "Cover": "Full-grain leather",
      "Dimensions": "A5 (148 × 210mm)",
      "Digital Sync": "iOS and Android app",
      "Weight": "320g",
    },
  },
];

export const getProductById = (id: string) =>
  products.find((p) => p.id === id);

export const getProductBySlug = (slug: string) =>
  products.find((p) => p.slug === slug);

export const getFeaturedProducts = () => products.filter((p) => p.featured);

export const getNewProducts = () => products.filter((p) => p.new);

export const getProductsByCategory = (category: string) =>
  products.filter((p) => p.category === category);

export const getRelatedProducts = (product: Product, limit = 4) =>
  products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, limit);
